### ISSUE TITLE
Allow to disable dependency on X11 on Linux

### ISSUE THREAD

**Issue by qarmin** [emrebicer/mouce#9]
My main target is `arm-linux-gnueabihf-gcc` which use Wayland on which I want to only set mouse position.
Current dependency on X11, require to setup complicated docker images to properly compile app.
With removed X11 I am able to compile lib with this simple command `build --target armv7-unknown-linux-gnueabihf`

**Comment by emrebicer** [comment]
With this [commit](https://github.com/emrebicer/mouce/commit/5ddd1d396a8388daeb7e83a7ac55ba6dbf3cc5a3),  ```x11``` is now introduced as a default feature. So by default, the library checks if the user is using x11, if not it defaults to uinput. However, since ```x11``` is a feature now, you can disable it explicitly;

If used as a library dependency, you can disable ```x11``` in your ```Cargo.toml``` by disabling default features;
```toml
[dependencies]
mouce = { version = "x.y.z", default-features = false }
```

or if compiling the cli executable;
```bash
cargo build --features="cli" --no-default-features --release
```
